language: android
dist: trusty
script:
- git fetch origin --tags
- "./gradlew assembleRelease"
git:
  submodules: true
jdk:
- openjdk9
before_install:
- openssl aes-256-cbc -K $encrypted_26e1bb6b6b4a_key -iv $encrypted_26e1bb6b6b4a_iv
  -in keystore.tar.enc -out keystore.tar -d
- tar xvf keystore.tar
- export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin
install:
- echo y | sdkmanager 'ndk-bundle'
- echo y | sdkmanager 'cmake;3.10.2.4988404'
- echo y | sdkmanager 'platform-tools'
- echo y | sdkmanager 'build-tools;29.0.1'
- echo y | sdkmanager 'platforms;android-29'
before_deploy:
- ./before_deploy.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: false
  local-dir: app/build/outputs/apk/
  on:
    branch: develop
env:
  global:
  - secure: 44HmwFFIKEmqnAOemuh8mIIbvglb3CZN+I+GsN7CGWn5Pvocg2sULj7sv33NDL6+5012bt3RoT9YgoTf2ERNR2W0bMVYw/0O5qdAnPiLD/v3SaoDv7qW3G9snKPBhdK72eODVxys66EY0oloJiBKQ/QnDr+HUiGpUuZlOaVLXBN9rcNlinM+4nMMSmaEOInhCwYrNI+NwOhoBVx+YNgaSqWBzHNYO7P2iWZfHbh9LmavpVynzp2gQp3VwoX9VrCrnfjLdRy+F0/TsWjiQ/PIbRJo2/Kl8SY93ve1SUfoJoLVTatX9ZG3a2+955+1SKBElI0mlKoMHDj0yy0F9zwUJY0rhbXnjp1EFyFgnRhCiaOKtXQp2+CKjig6V2kXRzxGzXKJ6aEZi8I3I6LKMgasXDgJgyzWmZjI30zBjA/lbWvmlLOkJswxFvQn972hPvhaE3P40OELrEu5uZiCJItkb4rWD2CPMkdz6R5mqbLa6Zn8RthfUyYuD8jh24lasp0wo9a3ARAhaZZnrxIS2p4QFugXzjsp28u4fA8pQDcKcHEZU0/fgun6gKKKkgq/DiIlheWiVO5Y7cnIiSKMYYkqlxiKpP2EbY5nE7yKwXANC+lvNQVBlk1mTP6POD5qeyAj75SeVc52VLAmvvVMKWZHD29KWW3f7JmIOTgrXHcSSck=
